export const tokens = {
  colors: {
    primary: '#9b2f00',
    onPrimary: '#ffffff',
    primaryContainer: '#c2410c',
    onPrimaryContainer: '#ffece7',
    secondary: '#5b598c',
    onSecondary: '#ffffff',
    secondaryContainer: '#c7c3fe',
    onSecondaryContainer: '#514f81',
    tertiary: '#6c5100',
    onTertiary: '#ffffff',
    tertiaryContainer: '#8a6800',
    onTertiaryContainer: '#ffeed1',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    background: '#faf9f5',
    onBackground: '#1b1c1a',
    surface: '#faf9f5',
    onSurface: '#1b1c1a',
    surfaceVariant: '#e3e2df',
    onSurfaceVariant: '#59413a',
    outline: '#8d7168',
    outlineVariant: '#e1bfb5',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f4f4f0',
    surfaceContainer: '#efeeea',
    surfaceContainerHigh: '#e9e8e4',
    surfaceContainerHighest: '#e3e2df',
    inverseSurface: '#2f312e',
    inverseOnSurface: '#f2f1ed',
    inversePrimary: '#ffb59d',
  },
  radius: {
    default: '0.25rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  spacing: {
    stackSm: '8px',
    gutter: '16px',
    touchTarget: '48px',
    stackMd: '16px',
    containerPadding: '24px',
    stackLg: '32px',
  }
};
export type Tokens = typeof tokens;
